const API_URL = localStorage.getItem('vendorPurchaseApiUrl') || '';
const app = document.getElementById('app');
const state = { user:null, products:[], batches:[], filter:'', loading:false };

function money(v){ const n=Number(v); return Number.isFinite(n) ? `₹${n.toLocaleString('en-IN',{maximumFractionDigits:2})}` : '—'; }
function esc(v){ return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])); }
function toast(msg){ const x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),2800); }
function imageUrl(p){ return p['Product Image']||p['Image']||p['Image Link']||p['Product Image Link']||p['Image URL']||''; }
function productKey(p){ return p.SKU_ID || p.SKU || p['Product SKU'] || p['Product Name']; }

async function api(action,payload={}){
  if(!API_URL) throw new Error('Apps Script URL not configured');
  const res=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});
  const data=await res.json(); if(!data.success) throw new Error(data.message||'Request failed'); return data;
}

function renderLogin(){
  app.innerHTML=`<main class="login"><section class="login-card"><div class="brand">MULTYBYTE<span>.</span></div><div class="eyebrow" style="margin-top:30px">Vendor Purchase OS</div><h1>Procurement, simplified.</h1><p>Secure workspace for vendor purchase requests, pricing and procurement communication.</p><form id="loginForm"><div class="field"><label>Email</label><input id="email" type="email" required autocomplete="username"></div><div class="field"><label>Password</label><input id="password" type="password" required autocomplete="current-password"></div><button class="btn btn-primary" style="width:100%">Sign in</button></form><div class="notice" style="margin-top:18px">Admin connects the MASTER catalog. Vendors see only products assigned to them.</div></section></main>`;
  document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('login',{email:email.value,password:password.value});state.user=d.user;localStorage.setItem('vendorPurchaseSession',d.sessionToken);await loadApp();}catch(err){toast(err.message)}};
}

async function loadApp(){ renderShell(); try{ const d=await api('getProducts',{sessionToken:localStorage.getItem('vendorPurchaseSession')}); state.products=d.products||[]; if(state.user.role==='Admin'){const s=await api('getDashboardStats',{sessionToken:localStorage.getItem('vendorPurchaseSession')});document.getElementById('statProducts').textContent=s.stats.totalProducts??0;document.getElementById('statVendors').textContent=s.stats.totalVendors??0;} renderProducts(); }catch(e){toast(e.message)} }
function renderShell(){
  app.innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand">MULTYBYTE<span>.</span></div><div class="top-actions"><span class="role">${esc(state.user.role)}</span><span class="muted" style="font-size:12px">${esc(state.user.email)}</span><button id="logout" class="btn btn-ghost">Logout</button></div></header><main class="content"><section class="hero"><div><div class="eyebrow">Vendor Purchase</div><h1>Purchase workspace</h1><p>Build purchase requests with clear pricing and direct procurement communication.</p></div><button class="btn btn-lime" id="newBatch">+ New Purchase</button></section><section class="stats"><div class="stat"><small>Products available</small><strong id="statProducts">—</strong></div><div class="stat"><small>Vendors</small><strong id="statVendors">${state.user.role==='Admin'?'—':'Restricted'}</strong></div><div class="stat"><small>Purchase quantity</small><strong id="statQty">0</strong></div><div class="stat"><small>Selected value</small><strong id="statValue">₹0</strong></div></section><section class="workspace"><div class="toolbar"><input class="field search" id="search" placeholder="Search product name or SKU…"><select id="category"><option value="">All categories</option></select><button class="btn btn-ghost" id="refresh">Refresh</button></div><div class="table-wrap"><table class="products"><thead><tr><th>Product</th><th>SKU</th><th>MRP</th><th>Purchase Quantity</th><th>Box Size</th><th>Price</th><th>Remark / Conversation</th><th>Freight Included</th><th>Action</th></tr></thead><tbody id="rows"></tbody></table></div></section></main></div>`;
  logout.onclick=async()=>{try{await api('logout',{sessionToken:localStorage.getItem('vendorPurchaseSession')})}catch{} localStorage.removeItem('vendorPurchaseSession');state.user=null;renderLogin()};
  refresh.onclick=loadApp; newBatch.onclick=()=>toast('Select product quantities below, then use Save Purchase.'); search.oninput=renderProducts; category.onchange=renderProducts;
}
function renderProducts(){
  const q=(search?.value||'').toLowerCase(); const cat=category?.value||'';
  const filtered=state.products.filter(p=>(!q||`${p['Product Name']||''} ${productKey(p)||''}`.toLowerCase().includes(q))&&(!cat||p.Categories===cat));
  if(category && category.options.length===1){[...new Set(state.products.map(p=>p.Categories).filter(Boolean))].sort().forEach(c=>category.add(new Option(c,c)));}
  const rows=document.getElementById('rows');
  rows.innerHTML=filtered.map((p,i)=>{const key=esc(productKey(p)); const img=imageUrl(p);return `<tr data-key="${key}"><td><div class="product">${img?`<img class="thumb" src="${esc(img)}" loading="lazy" onerror="this.outerHTML='<div class=\"thumb thumb-fallback\">No image</div>'">`:'<div class="thumb thumb-fallback">No image</div>'}<div><strong>${esc(p['Product Name'])}</strong><div class="muted" style="font-size:11px;margin-top:4px">${esc(p['Brand Name']||'')}</div></div></div></td><td><span class="locked">${key}</span></td><td class="fixed">${money(p.MRP)}</td><td><input class="qty-input" type="number" min="0" step="1" value="" data-field="qty" placeholder="Units"></td><td class="fixed">${esc(p['Box Size']||'—')}</td><td><input class="price-input" type="number" min="0" step="0.01" data-field="price" placeholder="₹ Price"></td><td><textarea class="remark" data-field="remark" placeholder="Add remark / reply…"></textarea></td><td><div class="freight"><label><input type="radio" name="fr_${i}" value="Yes"> Yes</label><label><input type="radio" name="fr_${i}" value="No" checked> No</label></div></td><td><button class="btn btn-primary save-row">Save</button></td></tr>`}).join('')||`<tr><td colspan="9" class="empty">No products found.</td></tr>`;
  rows.querySelectorAll('.save-row').forEach(b=>b.onclick=saveRow); updateTotals(); rows.querySelectorAll('input,textarea').forEach(x=>x.addEventListener('input',updateTotals));
}
function updateTotals(){let qty=0,val=0;document.querySelectorAll('tr[data-key]').forEach(r=>{qty+=Number(r.querySelector('[data-field="qty"]')?.value||0);val+=Number(r.querySelector('[data-field="qty"]')?.value||0)*Number(r.querySelector('[data-field="price"]')?.value||0)});if(document.getElementById('statQty'))statQty.textContent=qty.toLocaleString('en-IN');if(document.getElementById('statValue'))statValue.textContent=money(val)}
async function saveRow(e){const tr=e.target.closest('tr');const p=state.products.find(x=>String(productKey(x))===tr.dataset.key);const qty=Number(tr.querySelector('[data-field="qty"]').value);if(!qty||qty<1){toast('Enter the amount of units you want to purchase.');return}const price=Number(tr.querySelector('[data-field="price"]').value||0);const remark=tr.querySelector('[data-field="remark"]').value;const freight=tr.querySelector('input[name^="fr_"]:checked')?.value||'No';try{await api('savePurchaseItem',{sessionToken:localStorage.getItem('vendorPurchaseSession'),productSku:productKey(p),productName:p['Product Name'],quantity:qty,price,remark,freightIncluded:freight});toast('Purchase item saved.');}catch(err){toast(err.message)}}

(async()=>{const token=localStorage.getItem('vendorPurchaseSession');if(token){try{const d=await api('getSession',{sessionToken:token});state.user=d.user;await loadApp();}catch{localStorage.removeItem('vendorPurchaseSession');renderLogin()}}else renderLogin()})();